# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: EMOPIA
description: >- # this means to ignore newlines until "baseurl:"
  A emotion-labeled pop Piano music dataset
baseurl: "/bay" # the subpath of the site
url: "https://annahung31.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: EMOPIA
      slug: /
    - name: Classification
    - name: Generation

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: emopia.musicailab@gmail.com
      link: mailto:emopia.musicailab@gmail.com

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
